services:
  web:
    build:
      context: frontend
      target: development
    ports:
      - 5174:5174
    volumes:
      - ./frontend:/project
      - /project/node_modules
  db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always

      environment:
        MYSQL_ROOT_PASSWORD: example
        MYSQL_DATABASE: example
        MYSQL_USER: example
        MYSQL_PASSWORD: example
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql

  go-app:
    build: 
      context: backend
      target: dev
    command: sh -c "sleep 5 && air serve"
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      APP_NAME: SIR
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      DB_USERNAME: example
      DB_PASSWORD: example
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: example
    volumes:
      - ./backend:/app/


volumes:
  db_data: